src/objects/Contact_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <label>Contact Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactRelationship.cls
public class ContactRelationship {

    public void createContactRelationshipByContact(list<Contact> List_Contacts)
    {
           list<Contact_Relationship__c> ConList= new list<Contact_Relationship__c>();

        for(Contact c : List_Contacts)
    {
        if (c.Contact_Relationship__c==true)
        {
          Contact_Relationship__c cr = new Contact_Relationship__c();
            cr.Name = c.LastName;
            cr.Contact__c= c.Id;
            ConList.add(cr);
        }
    }
    insert ConlIst;

    }
}